runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: http://localhost:3000
- url: /.*
  script: main.app


